# Generated by Django 3.2 on 2022-08-18 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220818_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='extra_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='extra_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 12, 36, 40, 31270, tzinfo=utc)),
        ),
    ]
