# Generated by Django 3.2 on 2022-08-18 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220818_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='extra_price',
            new_name='start_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 12, 37, 42, 367247, tzinfo=utc)),
        ),
    ]
