# Generated by Django 3.2 on 2022-08-18 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20220818_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
